[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
